server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    druid:
      initial-size: 8
      min-idle: 4
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      username: root
      password: Fu214849135sl
      url: jdbc:mysql://120.26.168.94:3306/antq?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    # 参见 org.springframework.boot.autoconfigure.quartz.QuartzProperties
    job-store-type: JDBC
    wait-for-jobs-to-complete-on-shutdown: true
    scheduler-name: Antq-Quartz-Scheduler
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
      org.quartz.jobStore.misfireThreshold: 1000
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      # 在调度流程的第一步，也就是拉取待即将触发的triggers时，是上锁的状态，即不会同时存在多个线程拉取到相同的trigger的情况，也就避免的重复调度的危险。参考：https://segmentfault.com/a/1190000015492260
      org.quartz.jobStore.acquireTriggersWithinLock: true
pagehelper:
  auto-dialect: true
  helper-dialect: mysql
  reasonable: true
  params: count=countSql

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qezhhnjy.antq.quartz.entity
  global-config:
    db-config:
      id-type: assign_id
    banner: false
  configuration:
    #开启驼峰自动转换
    map-underscore-to-camel-case: true