#### 调度中心JDBC链接：链接地址请保持和 2.1章节 所创建的调度数据库的地址一致
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#spring.datasource.username=root
#spring.datasource.password=root_pwd
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  ### 报警邮箱
#spring.mail.host=smtp.qq.com
#spring.mail.port=25
#spring.mail.username=xxx@qq.com
#spring.mail.password=xxx
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#  ### 调度中心通讯TOKEN [选填]：非空时启用；
#xxl.job.accessToken=
#  ### 调度中心国际化配置 [必填]： 默认为 "zh_CN"/中文简体, 可选范围为 "zh_CN"/中文简体, "zh_TC"/中文繁体 and "en"/英文；
#xxl.job.i18n=zh_CN
#  ## 调度线程池最大线程配置【必填】
#xxl.job.triggerpool.fast.max=200
#xxl.job.triggerpool.slow.max=100
#  ### 调度中心日志表数据保存天数 [必填]：过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能；
#xxl.job.logretentiondays=30

server:
  port: 11005

spring:
  #  #配置静态资源
  #  mvc:
  #    static-path-pattern: /**
  #  resource:
  #    static-locations: classpath:/static/
  #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/xxl_job?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: Fu214849135sl
    driver-class-name: com.mysql.cj.jdbc.Driver

xxl:
  job:
    i18n: zh_CN
    triggerpool:
      fast:
        max: 100
      slow:
        max: 50
    logretentiondays: 30

record:

