mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    druid:
      initial-size: 8
      min-idle: 4
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      username: root
      password: aims2016
      url: jdbc:mysql://192.168.16.28/antq?useUnicode=true&useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 3000
    password: aims2016

logging:
  file:
    path: E:\log
  level:
    com.aims.jpx: debug
    org.apache.ibatis.logging: debug
