mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    druid:
      initial-size: 8
      min-idle: 4
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      username: root
      password: Fu214849135sl
      url: jdbc:mysql://localhost:3306/antq?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 3000
    password: aims2016

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    time-zone: GMT+8
    locale: zh_CN

  boot:
    admin:
      client:
        url: http://localhost:11003/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
